use_frameworks!
source 'https://github.com/Steven0351/private-spec-repo'
target 'SwiftyTesseractRTE_Example' do
  pod 'SwiftyTesseractRTE', :path => '../'
  pod 'SwiftyTesseract'
  target 'SwiftyTesseractRTE_Tests' do
    inherit! :search_paths
    
    
  end
end
